### ISSUE TITLE
Problem on docker

### ISSUE THREAD

**Issue by mxsl-gr** [Microsoft/napajs#164] opened 2017-12-19 02:49 UTC
# Problem

## image node:alpine

```
docker run -ti node:alpine sh

# npm install napajs
# node -e "require('napajs')"
```

error:
```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /node_modules/napajs/bin/napa-binding.node)
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
```

## image node

```
docker run -ti node bash

# npm install napajs
# node -e "require('napajs')"
```

error:
```
WARN napajs binding Thanks for using Napa.js.
WARN napajs binding There is a compatibility issue on Node v8.5.0 and above.
WARN napajs binding The flag "--noincremental-marking" is set to disable V8 incremental marking as a workaround.
WARN napajs binding We are working with Node.js team on a fix in newer Node versions.
module.js:689
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /node_modules/napajs/bin/napa-binding.node)
    at Object.Module._extensions..node (module.js:689:18)
    at Module.load (module.js:573:32)
```

**Comment by mxsl-gr** [comment] 2017-12-19 03:09
# solution node:alpine

install glibc on dockerfile.

```
ENV GLIBC_VERSION 2.25-r0

# Download and install glibc
RUN apk add --update curl && \
  curl -Lo /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub && \
  curl -Lo glibc.apk "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk" && \
  curl -Lo glibc-bin.apk "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk" && \
  apk add glibc-bin.apk glibc.apk && \
  /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib && \
  echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
  apk del curl && \
  rm -rf glibc.apk glibc-bin.apk /var/cache/apk/*
```

**Comment by tuananh** [comment] 2017-12-19 03:38
this is not a bug right? it's the problem with alpine because alpine is using musl instead of glibc

**Comment by mxsl-gr** [comment] 2017-12-19 05:52
@tuananh right. 
installed `glibc`, `require('napajs')` is work.
but run example on node:8-alpine:
```
var napa = require('napajs');
var zone1 = napa.zone.create('zone1', { workers: 4 }); // error
```
get error: `Segmentation fault`. track issue #96 
use 8.4-alpine not work...
use 6-alpine, get: 
```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Error relocating /app/node_modules/napajs/bin/napa-binding.node: __vsnprintf_chk: symbol not found
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
```

**Comment by mxsl-gr** [comment] 2017-12-19 07:45
I try call `./node_modules/napajs/bin/napa-binding.node` on terminal
my mac zsh:
```
zsh: exec format error: ./node_modules/napajs/bin/napa-binding.node
```

on docker `node-alpine`, `node`, `centos install nodejs`, always print `Segmentation fault`.
it's normal?

**Comment by helloshuangzi** [comment] 2017-12-19 19:21
Thanks for your feedback @mxsl-gr and @tuananh.  We haven't put any effort to tune napajs with Docker so far, but let me start to it now.

**Comment by mxsl-gr** [comment] 2017-12-20 02:03
@helloshuangzi thanks for reply. 
i try to use image `node:8-stretch`, example is working.

# temporary solution
```
docker run -ti node:8-stretch bash

# npm install napajs
# node -e "\
const napa = require('napajs'); \
const zone1 = napa.zone.create('zone1', { workers: 4 }); \
zone1.broadcast('console.log(\"hello world\");'); \
"
```

**Comment by helloshuangzi** [comment] 2017-12-21 00:38
Great to know, @mxsl-gr.
After a short investigation about Docker, to my current knowledge, I would say it's hard for a team to validate napa.js for all those existing node images. But it's a good point to make an docker image with node and napajs. It will allow docker users to taste napajs with the least effort to set their environment. 
I just create #166 (Priority 2) to track this item.  
Always welcome your feedback and contribution!

**Comment by helloshuangzi** [comment] 2017-12-22 20:05
Close it as the question is resolved, and let's track the following up item by #166

**Closed by helloshuangzi** 2017-12-22 20:05 UTC
Labels: investigating
