### ISSUE TITLE
Napa & Node Cluster

### ISSUE THREAD

**Issue by gustavomassa** [microsoft/napajs#185] opened 2018-01-16 18:37 UTC
Hello,

I would like to understand the relationship betwheen napa and node cluster, on the example we can determine the number of worker per zone. How exactly napajs creates a zone, napajs is single-core or does it uses node cluster internally?
Using node cluster we can have 1 worker per processor's core, so my idea is to have "N Napa Threads" per node cluster worker. Is it possible? 

Thank you!

**Comment by helloshuangzi** [comment] 2018-01-16 19:08
Thanks for your interest @gustavomassa .
napa doesn't have much to do with node cluster, it doesn't use node cluster internally. The most important difference is "A napa worker is back-ended by a thread, not like node cluster worker which is back-ended by a process". napa.js implemented its own thread pool. You can create multiple napa workers as different threads, and when tasks are assigned on them, they will be scheduled to any processors available in the system.

**Comment by gustavomassa** [comment] 2018-01-16 20:28
Thank you for the quick response @helloshuangzi 

I've runned a simple test using Node Cluster & NapaJs and the result is really exciting.
I have 4 cores on my computer, so for each core I've started a new thread.
```
import * as cluster from 'cluster';
import { ClusterMasterController } from './ClusterMasterController';
import { ClusterSlaveController } from './ClusterSlaveController';

//TEST
import * as napa from 'napajs';
import * as os from 'os';

if (cluster.isMaster) {
    //ClusterMasterController.Instance;

    //TEST MASTER
    console.log(`Cluster master pid ${process.pid} is running`);
    const numCPUs = os.cpus().length;
    console.log('cpus: ', numCPUs);
    for (let i = 0; i < numCPUs; i++) {
        cluster.fork({ name: `Worker ${i + 1}` });
    }

    cluster.on('exit', (worker, code, signal) => {
        console.log(`worker pid ${worker.process.pid} died, code ${code}, signal ${signal}`);
    });
} else {
    //ClusterSlaveController.Instance;

    //TEST WORKERS
    console.log(`Worker ${process.env.name} pid ${process.pid} started`);
    //TEST NAPA
    const zone1 = napa.zone.create('zone1', { workers: 1 });
    zone1.execute((text) => text, [`Worker ${process.env.name} pid ${process.pid} thread is running`]).then((result) => {
        //TEST CASE 1
        console.log(result.value);
        //TEST CASE 2
/*         while (true) {
            console.log(result.value);
        } */
    });
}
```
![image](https://user-images.githubusercontent.com/16235598/35010532-519a92bc-faea-11e7-80ee-43ca22034ff9.png)

I have further questions:
     1 - How can I get the thread info(id, name, execution time..)?
     2 - How I know which one of the threads has executed the function?
     3 - Can I set priorities on threads/functions?
     4 - What exactly is the definition of a zone, is it a thread pool?
     5 - Which scheduler algorithm is napajs using internally?
     6 - What is the thread execution time of each cycle of the scheduler?

Thank you!

**Comment by helloshuangzi** [comment] 2018-01-16 22:54
Before answering your questions, the above code logic can be achieve by napa.js itself without combining with node-cluster. You can just create napa zone with multiple workers, and call zone.execute to run tasks. napa scheduler will deal with load balance among napa workers.

1 - How can I get the thread info(id, name, execution time..)?
_Thread Id (napa worker Id) is not exposed as an API now._
2 - How I know which one of the threads has executed the function?
_As is answered in 1). Actually, multiple workers within a zone are symmetrical, so napa.js doesn't expect users to know anything about the different workers within a zone._
_The task will be FCFS assigned to the head idle worker in IdleWorker Queue with zone.execute._
_The task will be FCFS assigned to all the workers in the zone with zone.broadcast_
3 - Can I set priorities on threads/functions?
_no, napa.js has no priorities for its task so far, while you can create multiple zones within different settings, like # of workers, to achieve some relevant goals._
4 - What exactly is the definition of a zone, is it a thread pool?
_zone consists of multiple workers which are back-ended by threads. In terms of this, you can view a zone as a thread pool._
5 - Which scheduler algorithm is napajs using internally?
_Multiple napa workers of a zone pick up tasks assigned to the zone in FCFS._
6 - What is the thread execution time of each cycle of the scheduler?
_You can specify a timeout value when you call zone.execute. Besides this, napa.js doesn't have any other controlling._

**Comment by gustavomassa** [comment] 2018-01-17 11:56
@helloshuangzi  one more time, thank you for the quick responses.

Before I anwser new questions, let me understand something:

This is the Node cluster example, workers are sharing the tcp connection on the same port, so node cluster internally handle the requests and then dispatch to the workers dealing with load balancing. 
```
if (cluster.isMaster) {
  console.log(`Master ${process.pid} is running`);

  // Fork workers.
  for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
  }

  cluster.on('exit', (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });
} else {
  // Workers can share any TCP connection
  // In this case it is an HTTP server
  http.createServer((req, res) => {
    res.writeHead(200);
    res.end('hello world\n');
  }).listen(8000);

  console.log(`Worker ${process.pid} started`);
}
Although a primary use case for the cluster module is networking, it can also be used for other use cases requiring worker processes.
```
 1 - Can it be reproduced using NapaJS? 
 2 - Does NapaJS threads can share the same tcp connection and handle load balance for express requests like the node cluster?

==============================================================
Case 2: Let's supose we have a NapaJS zone with 2 workers running on a single core processor, the first function is an infinite loop, the second function is a console.log, since NapaJS scheduler uses FCFS, if the first function is served first, therefore the first function will run forever starving the processor, since the scheduler will not give any time slice for the second function to run, right?
I build this case tests and show the results.

Thank you!

**Comment by helloshuangzi** [comment] 2018-01-17 19:02
hi,
About the questions from the test case 1,  napa.js has no specific logic to deal with TCP connection sharing and the load balance at this level. It only fan out the incoming requests at threads (napa worker) level within a zone. Say, if you want to achieve a similar goal of this test case, a possible napa solution would be : 1) Create 1 http server listening to a port and create 1 zone with multiple workers; 2) call zone.execute to process the incoming request. napa will pick a idling worker to process the coming request, whiles all the multiple workers share the same TCP connection.

About the questions from the test case 2, you are right about the starving statement, and async/await can be used to call zone.execute.
I will try to reproduce the mentioned deadlock and async/await inside zone.exeuction problem.

**Comment by gustavomassa** [comment] 2018-01-17 22:12
hey @helloshuangzi 

I've created a node cluster & napa test project using vscode and typescript.
Please take a look on the project, it is using node cluster with just one worker to simulate one single core processor, and using 2 workers for the napajs zone.
Please test the runLoop() and runLoop2() functions and watch the different execution of the code.
The await is never returned, and sometimes occurs deadlocks.

Instructions to compile the project:
 1 - npm install
 2 - gulp watch (Save the Main.ts to generate the dist folder)
 3 - node dist/Main.js

[Napa.zip](https://github.com/Microsoft/napajs/files/1640765/Napa.zip)

**Comment by helloshuangzi** [comment] 2018-01-19 01:41
Hi, @gustavomassa ,
1) napa.js supports async/await well in my verification.
2) I checked your below code, 
```ts
   let running = false;
    while (true) {
        if (!running) {
            running = true;
            runLoop2().then(result => {
                //this code is never reached...
                console.log('EXECUTED TASKS');
                running = false;
            }).catch(ex => {
                print(lock, ex);
            });
        }
    }
```
it equals to 
```ts
    runLoop2().then(result => {
        //this code is never reached...
        console.log('EXECUTED TASKS');
        running = false;
    }).catch(ex => {
        print(lock, ex);
    });
    while(true);
```

it is this 'while(true)' that blocks all the promises in the node event loop to be resolved.

**Comment by gustavomassa** [comment] 2018-01-26 12:24
Hi @helloshuangzi 

Thank you for checking the test code.

I thought nodejs would handle while(true) (starving) situations on the event loop, thank you for pointing it.
So in my conclusions:
Even thought the napajs uses FCFS, on the single-core test using napajs, both threads were being executed in parallelism, which is really good.
My next questions:
1 - What about implementing a roud-robin approach as well? So we could configure a zone based on FCFS or round-robin.
2 - How can I pass/bind the this context to the zone.execution, I don't like to pass everything as parameter to the task.

**Comment by AngefloMusic** [comment] 2018-03-14 19:00
Bump on this question, what is the optimal amount of threads per core, after doing some experimenting, 3-4 seems to be the most optimal in the real world benchmarking I did. Also if implemented with the cluster module, would this conflict at all, or impact the total number of workers?

**Comment by helloshuangzi** [comment] 2018-03-16 23:58
Really a good question!
What's the optimal # of threads per core? We haven't made effort to answer it so far, but it's an important point to be added to benchmark and user guidance.
About the Node cluster impact, i think it's a general problem about process & thread in a computer system. If you create threads in multi-processes, to my current knowledge, the number of threads should be added up to estimate "# of threads per core"

**Closed** 2019-12-10 21:04 UTC
Labels: question
