### ISSUE TITLE
Doesn't work on linux: Error: libnapa.so: cannot open shared object file

### ISSUE THREAD

**Issue by jagu-sayan** [Microsoft/napajs#72] opened 2017-10-18 15:48 UTC
When I install napajs and try to use it on linux :
![image](https://user-images.githubusercontent.com/1262860/31728390-7d871b52-b42c-11e7-9ea3-53ffbdd7117f.png)

When I try to build napajs from source with `--no-fetch` :
![image](https://user-images.githubusercontent.com/1262860/31728231-0145011c-b42c-11e7-8bbf-e25421691e07.png)

**Comment by mathieulj** [comment] 2017-10-18 17:17
I've seen the same behaviour and have managed to bypass it by setting the LD_LIBRARY_PATH environment variable to include the napa installation directory :
```
$ node -e "require('napajs')"
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libnapa.so: cannot open shared object file: No such file or directory
...
$ export LD_LIBRARY_PATH=~/node_modules/napajs/bin:$LD_LIBRARY_PATH
$ node -e "require('napajs')"
```

Unfortunatly my current system does not have a recent enough c++ runtime so I run into other errors afterwords but that is likely a seperate dependency issue.

**Comment by tamdrea** [comment] 2017-10-18 17:28
I've put
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./node_modules/napajs/bin/
export LD_LIBRARY_PATH

Works for me.

**Comment by mathieulj** [comment] 2017-10-18 17:41
Confirmed working for me as well when i run it on more recent installation.

```
$ sudo docker run -it debian:stretch /bin/bash
# apt update && apt-get -y install apt-transport-https ca-certificates curl gnupg2
# curl https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
# echo "deb https://deb.nodesource.com/node_6.x jessie main" > /etc/apt/sources.list.d/nodesource.list
# apt update && apt install -y nodejs
# npm install napajs
# node -e "require('napajs')"
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libnapa.so: cannot open shared object file: No such file or directory
# export LD_LIBRARY_PATH=/node_modules/napajs/bin:$LD_LIBRARY_PATH
# node -e "require('napajs')"
// no error //
```

**Comment by fs-eire** [comment] 2017-10-18 22:57
Created bug #80 for this issue. Thanks for reporting!

**Comment by daiyip** [comment] 2017-10-19 07:22
Closed as duplicated.

**Closed by daiyip** 2017-10-19 07:22 UTC
